#!/usr/bin/env bash

alias be='bundle exec'
alias serve='python -m SimpleHTTPServer'
alias open-pr='pull-report --org animoto --pr-url --html | bcat --title="Open Pull Requests"'

# alias 9p="$PLAN9/bin/9p"
# alias plumber="$PLAN9/bin/plumber"
# alias 9pserve="$PLAN9/bin/9pserve"