#!/usr/bin/env bash

alias be='bundle exec'
alias serve='python -m SimpleHTTPServer'


# Prune dangling and orphaned volumes
alias prune-docker-volumes='docker volume rm $(docker volume ls -qf dangling=true)'
# Prune dangling or untagged images
alias prune-docker-images='docker rmi $(docker images -q -f dangling=true)'

alias dc='docker-compose'

# alias 9p="$PLAN9/bin/9p"
# alias plumber="$PLAN9/bin/plumber"
# alias 9pserve="$PLAN9/bin/9pserve"
