#!/usr/bin/env bash

# Setup editor to be handy-dandy editor helper script
export EDITOR=edit

# Set default Ruby options.
export RUBYOPT="-r rubygems"  # Always require rubygems.

export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1

# HAPPY_STATUS=' \xE2\xAD\x90\xEF\xB8\x8F  ' # Emoji Star
# SAD_STATUS=' \xF0\x9F\x92\x94  ' # Emoji broken heart
HAPPY_STATUS=" ${txtylw}☀${txtrst}  "
SAD_STATUS=" ${txtred}☠${txtrst} "

# Set the prompt __git_ps1 sets git status taking the '\W' as an arg. Then set
# the exit status indicator (also an agrument to __git_ps1. Then set update 
# Terminal.app's cwd so that new windows and tabs open in same location.
export PROMPT_COMMAND='__git_ps1 "\W" "$(exitstatus_prompt "${HAPPY_STATUS}" "${SAD_STATUS}")"; update_terminal_cwd'

# Set colors for `ls`
# NB: In some *nixes, this environment may be any of the following:
# * LS_COLORS
# * LSCOLORS
export CLICOLOR="exfxcxdxbxegedabagacad"

# Set RACK_ENV and ANIMOTO_DIR to some reasonable defaults
export RACK_ENV=development
export ANIMOTO_DIR=$HOME/Documents/Animoto/src/stack/config

export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

PATH=$PATH:$HOME/Local/bin # Local bin directory for my scripts
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:/usr/local/share/npm/bin # Add node.js npm binaries

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libxml2/lib/pkgconfig # OS-X libxml2

export GOPATH=$HOME/Local/golib

### Added by the Heroku Toolbelt
PATH="/usr/local/heroku/bin:$PATH"

export PATH
