#!/usr/bin/env bash

# Setup editor to be handy-dandy editor helper script
export EDITOR=edit
export VISUAL="$EDITOR"

# Set default Ruby options.
export RUBYOPT="-r rubygems"  # Always require rubygems.


export PROMPT_COMMAND='__prompt_command'

# Set colors for `ls`
# NB: In some *nixes, this environment may be any of the following:
# * LS_COLORS
# * LSCOLORS
export CLICOLOR="exfxcxdxbxegedabagacad"

# Set RACK_ENV and ANIMOTO_DIR to some reasonable defaults
export RACK_ENV=development
export ANIMOTO_DIR=$HOME/Documents/Animoto/src/stack/config

export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

PATH=$PATH:$HOME/.dotfiles/bin
PATH=$PATH:$HOME/Local/bin # Local bin directory for my scripts
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:/usr/local/share/npm/bin # Add node.js npm binaries

export MYPATHS="/Users/lritter/Documents/Animoto/src/stackimoto/applications:/Users/lritter/Documents/Animoto/src/packages:/Users/lritter/.dotfiles"

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libxml2/lib/pkgconfig # OS-X libxml2

export GOPATH=$HOME/Local/golib
export GOPATHBIN="${GOPATH}"/bin

### Added by the Heroku Toolbelt
HEROKU_TOOLBELT_PATH="/usr/local/heroku/bin"

export PATH="$HEROKU_TOOLBELT_PATH:$GOPATHBIN:$PATH"

PERL_MB_OPT="--install_base \"/Users/lritter/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/lritter/perl5"; export PERL_MM_OPT;
