#!/usr/bin/env bash

# Setup editor to be handy-dandy editor helper script
export EDITOR=edit
export VISUAL="$EDITOR"

# Set default Ruby options.
export RUBYOPT="-r rubygems"  # Always require rubygems.

# if [ "$TERM" != "dumb" ]
# then
#   export FANCY_PROMPT="YES"
#   export PROMPT_COMMAND='__prompt_command'
# else
#   export PROMPT_COMMAND=""
#   export FANCY_PROMPT="NO"
# fi

export ACME_DEFAULT="/Users/lritter/.dotfiles/acme/ACME_DEFAULT"

# Set colors for `ls`
# NB: In some *nixes, this environment may be any of the following:
# * LS_COLORS
# * LSCOLORS
export CLICOLOR="exfxcxdxbxegedabagacad"

# Set RACK_ENV and ANIMOTO_DIR to some reasonable defaults
export RACK_ENV=development
export ANIMOTO_STACK_ROOT=/Users/lritter/Documents/Animoto/src/stack
export ANIMOTO_DIR=${ANIMOTO_STACK_ROOT}/config

export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

PATH=$PATH:$HOME/.dotfiles/bin
PATH=$PATH:$HOME/Local/bin # Local bin directory for my scripts
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:/usr/local/share/npm/bin # Add node.js npm binaries

export MYPATHS="/Users/lritter/Documents/Animoto/src/stack/applications:/Users/lritter/Documents/Animoto/src/packages:/Users/lritter/Documents/Projects:/Users/lritter/Documents:/Users/lritter"

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libxml2/lib/pkgconfig # OS-X libxml2

export GOPATH=$HOME/Local/golib
export GOPATHBIN="${GOPATH}"/bin

### Added by the Heroku Toolbelt
HEROKU_TOOLBELT_PATH="/usr/local/heroku/bin"

### PLAN9
export PLAN9=/usr/local/Cellar/plan9port/HEAD/libexec
# PATH=$PATH:$PLAN9/bin

export PATH="$HEROKU_TOOLBELT_PATH:$GOPATHBIN:$PATH"

PERL_MB_OPT="--install_base \"/Users/lritter/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/lritter/perl5"; export PERL_MM_OPT;
