#!/usr/bin/env bash

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh

# Add tab completion for SSH in known_hosts.
# NB: need to figure out how to do this and the ssh config completion since
#     right now I'm overwriting
[ -e "$HOME/.ssh/known_hosts" ] && complete -o "default" -o "nospace" -W "$(cat ~/.ssh/known_hosts | cut -d " " -f1 | cut -d , -f1 | tr ' ' '\n')" scp sftp ssh

# Make sure to install bash-completion with homebrew
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# source <(jira completion bash)